//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_TOKENS
    {
        public int ID { get; set; }
        public int GRL_TOKENS_TIPOS_ID { get; set; }
        public string TOKEN { get; set; }
        public string CONTEUDO { get; set; }
        public System.DateTime DATA { get; set; }
        public Nullable<int> INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GRL_TOKENS_TIPOS GRL_TOKENS_TIPOS { get; set; }
    }
}
