//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_ARQUIVOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRL_ARQUIVOS()
        {
            this.GT_Exercicio_ARQUIVOS = new HashSet<GT_Exercicio_ARQUIVOS>();
            this.INST_APLICACAO_ARQUIVOS = new HashSet<INST_APLICACAO_ARQUIVOS>();
            this.PES_ARQUIVOS = new HashSet<PES_ARQUIVOS>();
        }
    
        public int ID { get; set; }
        public int GRL_ARQUIVOS_TIPO_DOCS_ID { get; set; }
        public string NOME { get; set; }
        public string ALT { get; set; }
        public string TIPO { get; set; }
        public int TAMANHO { get; set; }
        public string CAMINHO_URL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GRL_ARQUIVOS_TIPO_DOCS GRL_ARQUIVOS_TIPO_DOCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GT_Exercicio_ARQUIVOS> GT_Exercicio_ARQUIVOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INST_APLICACAO_ARQUIVOS> INST_APLICACAO_ARQUIVOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_ARQUIVOS> PES_ARQUIVOS { get; set; }
    }
}
