//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_DEFINICOES
    {
        public int ID { get; set; }
        public int INST_APLICACAO_ID { get; set; }
        public string INST_PER_TEMA_1 { get; set; }
        public string INST_PER_TEMA_1_SIDEBAR { get; set; }
        public string INST_PER_TEMA_2 { get; set; }
        public Nullable<int> INST_PER_LOGOTIPO_WIDTH { get; set; }
        public Nullable<int> INST_MDL_GPAG_MOEDA_PADRAO { get; set; }
        public Nullable<int> INST_MDL_GPAG_N_DIGITOS_VALORES_PAGAMENTOS { get; set; }
        public Nullable<int> INST_MDL_GPAG_NOTA_DECIMAL { get; set; }
        public Nullable<int> SEC_SENHA_TENT_BLOQUEIO { get; set; }
        public Nullable<int> SEC_SENHA_TENT_BLOQUEIO_TEMPO { get; set; }
        public Nullable<int> SEC_SENHA_RECU_LIMITE_EMAIL { get; set; }
        public Nullable<int> SEC_SESSAO_TIMEOUT_TEMPO { get; set; }
        public string NET_STMP_HOST { get; set; }
        public Nullable<int> NET_STMP_PORT { get; set; }
        public string NET_SMTP_USERNAME { get; set; }
        public string NET_SMTP_SENHA { get; set; }
        public string NET_SMTP_FROM { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual INST_APLICACAO INST_APLICACAO { get; set; }
    }
}
