//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_Exercicio_targetMuscles
    {
        public int ID { get; set; }
        public int GT_Exercicio_ID { get; set; }
        public int GT_targetMuscles_ID { get; set; }
    
        public virtual GT_Exercicio GT_Exercicio { get; set; }
        public virtual GT_targetMuscles GT_targetMuscles { get; set; }
    }
}
