//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespPessoaIdosa
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public int GT_TipoTestePessoaIdosa_ID { get; set; }
        public Nullable<decimal> PERCMG { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string VALOR_DESEJAVEL { get; set; }
        public Nullable<decimal> RESP_SUMMARY { get; set; }
        public string RES_DESCRICAO { get; set; }
        public Nullable<int> PERCENTIL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
        public virtual GT_TipoTestePessoaIdosa GT_TipoTestePessoaIdosa { get; set; }
    }
}
