//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespComposicao
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public int GT_TipoTesteComposicao_ID { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public string PESODESEJAVEL { get; set; }
        public Nullable<decimal> PESOPERDER { get; set; }
        public Nullable<int> PERIMETRO_ABDOMINAL { get; set; }
        public Nullable<int> PERIMETRO_CINTURA { get; set; }
        public Nullable<int> PERIMETRO_UMBIGO { get; set; }
        public Nullable<int> ABDOMINAL { get; set; }
        public Nullable<int> TRICIPITAL { get; set; }
        public Nullable<int> RESISTENCIA { get; set; }
        public Nullable<int> PREGASTRICIPITAL { get; set; }
        public Nullable<int> PREGASSUPRALLIACA { get; set; }
        public Nullable<int> PREGAS_ABDOMINAL { get; set; }
        public Nullable<int> PREGAS_SUBESCAPULAR { get; set; }
        public Nullable<int> PREGAS_PEITO { get; set; }
        public Nullable<decimal> PERCMG { get; set; }
        public Nullable<decimal> MIG { get; set; }
        public Nullable<decimal> MG { get; set; }
        public string MGDESEJAVEL { get; set; }
        public Nullable<decimal> METABOLISMO { get; set; }
        public Nullable<decimal> ESTIMACAO { get; set; }
        public Nullable<int> GT_TipoNivelActividade_ID { get; set; }
        public Nullable<decimal> RESP_SUMMARY { get; set; }
        public string RESP_DESCRICAO { get; set; }
        public Nullable<int> PERCENTIL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
        public virtual GT_TipoNivelActividade GT_TipoNivelActividade { get; set; }
        public virtual GT_TipoTesteComposicao GT_TipoTesteComposicao { get; set; }
    }
}
