//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespRisco
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public Nullable<bool> radIdade { get; set; }
        public Nullable<bool> radHeredMasc { get; set; }
        public Nullable<bool> radHeredFem { get; set; }
        public Nullable<bool> radTabacFuma { get; set; }
        public Nullable<bool> radTabacFuma6 { get; set; }
        public Nullable<int> txtCigarrosMedia { get; set; }
        public Nullable<bool> radTensao { get; set; }
        public Nullable<int> txtMaxSistolica { get; set; }
        public Nullable<int> txtMinSistolica { get; set; }
        public Nullable<int> txtMaxDistolica { get; set; }
        public Nullable<int> txtMinDistolica { get; set; }
        public Nullable<bool> radMedicacao { get; set; }
        public string txtMedicamento { get; set; }
        public Nullable<bool> radColesterol1 { get; set; }
        public Nullable<bool> radColesterol2 { get; set; }
        public Nullable<bool> radColesterol3 { get; set; }
        public Nullable<bool> radColesterol4 { get; set; }
        public Nullable<bool> radColesterol5 { get; set; }
        public Nullable<bool> radGlicose { get; set; }
        public Nullable<int> txtGlicose1 { get; set; }
        public Nullable<int> txtGlicose2 { get; set; }
        public Nullable<bool> radInactividade1 { get; set; }
        public Nullable<bool> radInactividade2 { get; set; }
        public Nullable<bool> radInactividade3 { get; set; }
        public Nullable<int> txtPerimetro { get; set; }
        public string txtCardiaca { get; set; }
        public string txtVascular { get; set; }
        public string txtCerebroVascular { get; set; }
        public string txtCardioVascularOutras { get; set; }
        public string txtObstrucao { get; set; }
        public string txtAsma { get; set; }
        public string txtFibrose { get; set; }
        public string txtPulmomarOutras { get; set; }
        public string txtDiabetes1 { get; set; }
        public string txtDiabetes2 { get; set; }
        public string txtTiroide { get; set; }
        public string txtRenais { get; set; }
        public string txtFigado { get; set; }
        public string txtMetabolicaOutras { get; set; }
        public Nullable<bool> chkDor { get; set; }
        public Nullable<bool> chkRespiracao { get; set; }
        public Nullable<bool> chkTonturas { get; set; }
        public Nullable<bool> chkDispeneia { get; set; }
        public Nullable<bool> chkEdema { get; set; }
        public Nullable<bool> chkPalpitacoes { get; set; }
        public Nullable<bool> chkClaudicacao { get; set; }
        public Nullable<bool> chkMurmurio { get; set; }
        public Nullable<bool> chkfadiga { get; set; }
        public Nullable<int> RESP_SUMMARY { get; set; }
        public string RESP_DESCRICAO { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
    }
}
