//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespForca
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public int GT_TipoTesteForca_ID { get; set; }
        public Nullable<decimal> CARGA { get; set; }
        public Nullable<int> REPETICOES90 { get; set; }
        public Nullable<decimal> VINICIAL { get; set; }
        public Nullable<int> NUM_ABDOMINAIS { get; set; }
        public Nullable<int> NUM_FLEXOES { get; set; }
        public Nullable<decimal> TENTATIVA1 { get; set; }
        public Nullable<decimal> TENTATIVA2 { get; set; }
        public Nullable<decimal> TENTATIVA3 { get; set; }
        public Nullable<decimal> TENTATIVA4 { get; set; }
        public Nullable<decimal> TENTATIVA5 { get; set; }
        public Nullable<decimal> TENTATIVA6 { get; set; }
        public Nullable<decimal> TENTATIVA7 { get; set; }
        public Nullable<decimal> TENTATIVA8 { get; set; }
        public Nullable<decimal> TENTATIVA9 { get; set; }
        public Nullable<decimal> TENTATIVA10 { get; set; }
        public Nullable<decimal> FADIGASPRINT { get; set; }
        public string DESEJAVEL { get; set; }
        public Nullable<decimal> RESP_SUMMARY { get; set; }
        public string RESP_DESCRICAO { get; set; }
        public Nullable<int> PERCENTIL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
        public virtual GT_TipoTesteForca GT_TipoTesteForca { get; set; }
    }
}
