//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespAptidaoCardioYMCA
    {
        public int ID { get; set; }
        public int GT_RespAptidaoCardio_ID { get; set; }
        public Nullable<decimal> CARGA1 { get; set; }
        public Nullable<decimal> CARGA2 { get; set; }
        public Nullable<decimal> CARGA3 { get; set; }
        public Nullable<decimal> CARGA4 { get; set; }
        public Nullable<decimal> TRAB1 { get; set; }
        public Nullable<decimal> TRAB2 { get; set; }
        public Nullable<decimal> TRAB3 { get; set; }
        public Nullable<decimal> TRAB4 { get; set; }
        public Nullable<decimal> POT1 { get; set; }
        public Nullable<decimal> POT2 { get; set; }
        public Nullable<decimal> POT3 { get; set; }
        public Nullable<decimal> POT4 { get; set; }
        public Nullable<decimal> VO21 { get; set; }
        public Nullable<decimal> VO22 { get; set; }
        public Nullable<decimal> VO23 { get; set; }
        public Nullable<decimal> VO24 { get; set; }
        public Nullable<decimal> FC1 { get; set; }
        public Nullable<decimal> FC2 { get; set; }
        public Nullable<decimal> FC3 { get; set; }
        public Nullable<decimal> FC4 { get; set; }
    
        public virtual GT_RespAptidaoCardio GT_RespAptidaoCardio { get; set; }
    }
}
