//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_SOCIOS_EVOLUCAO
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<decimal> ALTURA { get; set; }
        public Nullable<decimal> TADISTOLICA { get; set; }
        public Nullable<decimal> TASISTOLICA { get; set; }
        public int INSERIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
    }
}
