//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class INST_APLICACAO_ENDERECOS
    {
        public int ID { get; set; }
        public int INST_APLICACAO_ID { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string RUA { get; set; }
        public string MORADA { get; set; }
        public int ENDERECO_PAIS_ID { get; set; }
        public int GRL_ENDERECO_CIDADE_ID { get; set; }
        public int ENDERECO_MUN_DISTR_ID { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GRL_ENDERECO_CIDADE GRL_ENDERECO_CIDADE { get; set; }
        public virtual GRL_ENDERECO_MUN_DISTR GRL_ENDERECO_MUN_DISTR { get; set; }
        public virtual GRL_ENDERECO_PAIS GRL_ENDERECO_PAIS { get; set; }
        public virtual INST_APLICACAO INST_APLICACAO { get; set; }
    }
}
