//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class INST_APLICACAO_CONTACTOS
    {
        public int ID { get; set; }
        public int INST_APLICACAO_ID { get; set; }
        public decimal TELEFONE { get; set; }
        public Nullable<decimal> TELEFONE_ALTERNATIVO { get; set; }
        public Nullable<decimal> FAX { get; set; }
        public string EMAIL { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string URL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual INST_APLICACAO INST_APLICACAO { get; set; }
    }
}
