//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class PES_IDENTIFICACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PES_IDENTIFICACAO()
        {
            this.PES_IDENTIFICACAO_LOCAL_EM = new HashSet<PES_IDENTIFICACAO_LOCAL_EM>();
        }
    
        public int ID { get; set; }
        public int PES_PESSOAS_ID { get; set; }
        public int PES_TIPO_IDENTIFICACAO_ID { get; set; }
        public string NUMERO { get; set; }
        public System.DateTime DATA_EMISSAO { get; set; }
        public Nullable<System.DateTime> DATA_VALIDADE { get; set; }
        public string ORGAO_EMISSOR { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual PES_TIPO_IDENTIFICACAO PES_TIPO_IDENTIFICACAO { get; set; }
        public virtual PES_PESSOAS PES_PESSOAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_IDENTIFICACAO_LOCAL_EM> PES_IDENTIFICACAO_LOCAL_EM { get; set; }
    }
}
