//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class PES_PESSOAS_CARACT
    {
        public int ID { get; set; }
        public int PES_PESSOAS_ID { get; set; }
        public Nullable<int> PES_PESSOAS_TIPO_SANG_ID { get; set; }
        public Nullable<decimal> ALTURA { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<int> FCREPOUSO { get; set; }
        public Nullable<decimal> FCMAXIMO { get; set; }
        public Nullable<decimal> TASISTOLICA { get; set; }
        public Nullable<decimal> TADISTOLICA { get; set; }
        public Nullable<int> MASSAGORDA { get; set; }
        public Nullable<int> VO2 { get; set; }
        public Nullable<int> GT_DuracaoPlano_ID { get; set; }
        public Nullable<int> IMC { get; set; }
        public Nullable<decimal> FCTREINO1 { get; set; }
        public Nullable<decimal> FCTREINO2 { get; set; }
        public Nullable<decimal> FCTREINO3 { get; set; }
        public Nullable<decimal> FCTREINO4 { get; set; }
        public Nullable<decimal> FCTREINO5 { get; set; }
        public Nullable<decimal> FCTREINO6 { get; set; }
        public Nullable<decimal> FCTREINO7 { get; set; }
        public Nullable<decimal> FCTREINO8 { get; set; }
        public Nullable<decimal> FCTREINO9 { get; set; }
        public Nullable<decimal> FCTREINO10 { get; set; }
        public Nullable<bool> FR_HT { get; set; }
        public Nullable<bool> FR_TB { get; set; }
        public Nullable<bool> FR_HL { get; set; }
        public Nullable<bool> FR_OB { get; set; }
        public Nullable<bool> FR_DB { get; set; }
        public Nullable<bool> FR_IN { get; set; }
        public Nullable<bool> FR_HE { get; set; }
        public Nullable<bool> FR_EC { get; set; }
        public Nullable<bool> FR_OT { get; set; }
        public Nullable<bool> OB_AC { get; set; }
        public Nullable<bool> OB_CP { get; set; }
        public Nullable<bool> OB_PI { get; set; }
        public Nullable<bool> OB_TP { get; set; }
        public Nullable<bool> OB_AM { get; set; }
        public Nullable<bool> OB_BE { get; set; }
        public Nullable<bool> OB_TO { get; set; }
        public Nullable<bool> OB_OT { get; set; }
        public string OBSERVACOES { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_DuracaoPlano GT_DuracaoPlano { get; set; }
        public virtual PES_PESSOAS PES_PESSOAS { get; set; }
        public virtual PES_PESSOAS_CARACT_TIPO_SANG PES_PESSOAS_CARACT_TIPO_SANG { get; set; }
    }
}
