//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class PES_IDENTIFICACAO_LOCAL_EM
    {
        public int ID { get; set; }
        public int PES_IDENTIFICACAO_ID { get; set; }
        public int GRL_ENDERECO_PAIS_ID { get; set; }
        public int GRL_ENDERECO_CIDADE_ID { get; set; }
        public Nullable<int> GRL_ENDERECO_MUN_DISTR_ID { get; set; }
    
        public virtual GRL_ENDERECO_CIDADE GRL_ENDERECO_CIDADE { get; set; }
        public virtual GRL_ENDERECO_MUN_DISTR GRL_ENDERECO_MUN_DISTR { get; set; }
        public virtual GRL_ENDERECO_PAIS GRL_ENDERECO_PAIS { get; set; }
        public virtual PES_IDENTIFICACAO PES_IDENTIFICACAO { get; set; }
    }
}
