//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILIZADORES_LOGIN_LOGS
    {
        public int ID { get; set; }
        public int UTILIZADORES_ID { get; set; }
        public string ENDERECO_IP { get; set; }
        public string ENDERECO_MAC { get; set; }
        public string HOSPEDEIRO_HOST { get; set; }
        public string DISPOSITIVO { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> LONG { get; set; }
        public string URL { get; set; }
        public System.DateTime DATA { get; set; }
    
        public virtual UTILIZADORES UTILIZADORES { get; set; }
    }
}
