//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILIZADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILIZADORES()
        {
            this.PES_PESSOAS = new HashSet<PES_PESSOAS>();
            this.UTILIZADORES_ACESSO_UTIL_PERFIS = new HashSet<UTILIZADORES_ACESSO_UTIL_PERFIS>();
            this.UTILIZADORES_LOGIN_LOGS = new HashSet<UTILIZADORES_LOGIN_LOGS>();
            this.UTILIZADORES_ACESSO_UTIL_GRUPOS = new HashSet<UTILIZADORES_ACESSO_UTIL_GRUPOS>();
            this.UTILIZADORES_LOGIN_PASSWORD_TENT = new HashSet<UTILIZADORES_LOGIN_PASSWORD_TENT>();
        }
    
        public int ID { get; set; }
        public string LOGIN { get; set; }
        public string SENHA_PASSWORD { get; set; }
        public string SALT { get; set; }
        public bool VALIDA { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<System.DateTime> DATA_ACT { get; set; }
        public Nullable<System.DateTime> DATA_DESACT { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOAS> PES_PESSOAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILIZADORES_ACESSO_UTIL_PERFIS> UTILIZADORES_ACESSO_UTIL_PERFIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILIZADORES_LOGIN_LOGS> UTILIZADORES_LOGIN_LOGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILIZADORES_ACESSO_UTIL_GRUPOS> UTILIZADORES_ACESSO_UTIL_GRUPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILIZADORES_LOGIN_PASSWORD_TENT> UTILIZADORES_LOGIN_PASSWORD_TENT { get; set; }
    }
}
